services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    container_name: bank-churn-api

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8503:8501"
    depends_on:
      - api
    container_name: bank-churn-frontend